// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnYy2umHaN8zjAWb5QJ4nsZbrWVRW9NHw',
    appId: '1:807614042675:web:962ccb0eb7212ca9e34946',
    messagingSenderId: '807614042675',
    projectId: 'uaspm2',
    authDomain: 'uaspm2.firebaseapp.com',
    storageBucket: 'uaspm2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADl5R9ZcLvtZ27PLPRQTiYMc7HGxHbBg',
    appId: '1:807614042675:android:b27d5caefe6b93e8e34946',
    messagingSenderId: '807614042675',
    projectId: 'uaspm2',
    storageBucket: 'uaspm2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4YTg9CDxlCrbVRyFt9wMFsBSuoxmcqo',
    appId: '1:807614042675:ios:1500944847e0615de34946',
    messagingSenderId: '807614042675',
    projectId: 'uaspm2',
    storageBucket: 'uaspm2.appspot.com',
    iosClientId: '807614042675-l1jp1msqdn0cnugqrlclcghqu9qpr7fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasPm2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk4YTg9CDxlCrbVRyFt9wMFsBSuoxmcqo',
    appId: '1:807614042675:ios:79fcedae771a2244e34946',
    messagingSenderId: '807614042675',
    projectId: 'uaspm2',
    storageBucket: 'uaspm2.appspot.com',
    iosClientId: '807614042675-5pqvt7nu49l9el6mpae6ihi0v0vcuvgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasPm2.RunnerTests',
  );
}
